In [1]:
import pandas as pd
import numpy as np

In [2]:
input_path = "../../../Data/GHCND/montreal_summer_stats.csv"
df_summ = pd.read_csv(input_path)
df_summ

,Unnamed: 0,Year,SummerStart,SummerEnd,StartGrad,EndGrad,SummerLength,SummerAccHeat,SummerTmaxDay,SummerTavg
0,0,1961,170,263,0.155713,-0.180622,94,303.050000,247,294.011702
1,1,1962,155,242,0.121100,-0.144712,88,212.150000,189,293.242045
2,2,1963,154,233,0.203207,-0.121691,80,260.050000,209,293.761875
3,3,1964,147,241,0.177692,-0.112052,95,257.100000,181,292.879474
4,4,1965,156,243,0.127488,-0.134544,88,208.250000,227,292.873295
5,5,1966,160,239,0.226310,-0.182865,80,255.500000,184,294.073125
6,6,1967,161,252,0.158636,-0.211193,92,284.900000,202,293.942391
7,7,1968,167,257,0.103949,-0.143386,91,213.850000,196,292.768681
8,8,1969,163,252,0.188152,-0.179670,90,318.350000,198,294.121111
9,9,1970,155,254,0.213661,-0.129582,100,364.600000,211,294.366500
10,10,1971,155,256,0.201131,-0.119768,102,323.050000,181,293.985784
11,11,1972,153,251,0.151845,-0.182726,99,264.950000,196,293.322222
12,12,1973,157,253,0.196579,-0.240207,97,478.600000,189,295.687629
13,13,1974,162,242,0.191553,-0.199853,81,235.200000,195,293.988889
14,14,1975,146,243,0.292008,-0.144064,98,418.500000,213,295.103571
15,15,1976,155,239,0.178640,-0.157417,85,281.800000,187,294.269412
16,16,1977,156,236,0.171133,-0.158355,81,213.475000,201,293.094136
17,17,1978,150,240,0.202786,-0.165420,91,289.850000,201,293.899451
18,18,1979,159,242,0.133358,-0.191463,84,261.833333,206,293.584524
19,19,1980,164,248,0.126937,-0.225210,85,281.750000,176,294.261765
20,20,1981,158,237,0.225095,-0.205575,80,256.500000,189,294.159375
21,21,1982,156,237,0.153952,-0.143220,82,214.500000,199,293.177439
22,22,1983,159,257,0.234384,-0.199079,99,447.400000,185,295.452020
23,23,1984,154,240,0.226533,-0.194116,87,356.500000,160,295.063793
24,24,1985,144,230,0.149355,-0.140238,87,233.625000,203,293.343966
25,25,1986,168,240,0.085849,-0.155940,73,164.000000,206,292.704795
26,26,1987,152,242,0.131541,-0.210788,91,293.833333,191,293.952747
27,27,1988,147,147,0.206595,0.206595,1,3.750000,147,294.900000
28,28,1989,134,223,0.214480,-0.120243,90,307.050000,183,294.161667
29,29,1992,192,248,0.104176,-0.172195,57,88.824468,238,292.289931
30,30,1993,0,0,NaN,NaN,0,0.000000,86,0.000000
31,31,1997,157,239,0.189633,-0.153347,83,237.350000,178,293.831928
32,32,1998,147,252,0.145502,-0.142806,106,296.300000,196,293.396698
33,33,1999,146,239,0.159302,-0.188929,94,353.750000,155,294.552660
34,34,2000,170,240,0.171219,-0.149650,71,175.800000,177,293.420423
35,35,2001,155,256,0.115714,-0.204546,102,359.450000,166,294.300000
36,36,2002,168,257,0.165709,-0.284971,90,359.500000,184,294.975556
37,37,2003,164,250,0.140682,-0.216710,87,275.200000,177,293.962644
38,38,2004,165,244,0.153971,-0.136733,80,194.150000,203,293.176875
39,39,2005,155,257,0.177768,-0.204502,103,415.100000,179,294.903883
40,40,2006,156,243,0.145541,-0.210296,88,281.200000,213,293.915341
41,41,2007,154,258,0.098405,-0.184981,105,262.450000,214,292.866667
42,42,2008,154,254,0.135571,-0.173782,101,294.750000,189,293.793564
43,43,2009,169,245,0.167285,-0.209111,77,236.750000,229,293.962987
44,44,2010,153,248,0.166012,-0.185849,96,339.600000,187,294.292708
45,45,2011,157,251,0.196956,-0.179524,95,357.150000,202,294.736316
46,46,2012,153,252,0.191801,-0.196387,100,402.200000,172,294.979000
47,47,2013,154,253,0.160265,-0.138500,100,285.775000,196,293.412000
48,48,2014,133,214,0.229398,-0.160923,82,281.050000,146,294.088415
49,49,2015,159,257,0.057626,-0.264186,99,333.950000,210,294.455556
50,50,2016,154,261,0.190689,-0.206362,108,414.300000,223,294.604630
51,51,2017,151,271,0.179339,-0.183990,121,316.800000,268,293.153512
52,52,2018,152,256,0.228928,-0.257696,105,466.650000,183,295.215238
53,53,2019,160,251,0.200117,-0.222696,92,346.000000,201,294.656522
54,54,2020,154,243,0.276839,-0.211276,90,417.700000,191,295.503333
55,55,2021,147,265,0.123439,-0.229772,119,438.900000,233,294.522269
56,56,2022,154,251,0.158364,-0.174910,98,331.500000,202,294.232653
57,57,2023,151,261,0.145159,-0.197494,111,348.200000,187,293.889640

In [3]:
df_summ.query("(Year <=1970)").SummerLength.mean()

np.float64(89.8)

In [4]:
df_summ.query("(Year >=2014)").SummerLength.mean()

np.float64(102.5)

In [6]:
df_summ.query("(Year > 1990) & (Year <= 2000)").SummerLength.mean()

np.float64(68.5)

In [6]:
df_summ.query("(Year >=2014)").SummerEnd.mean()

np.float64(261.4)

In [5]:
df_summ.query("(Year <=1970)").SummerEnd.mean()

np.float64(248.8)

In [7]:
# toronto
input_path = "../../../Data/GHCND/toronto_ont_summer_stats.csv"
df_summ = pd.read_csv(input_path)
df_summ

,Unnamed: 0,Year,SummerStart,SummerEnd,StartGrad,EndGrad,SummerLength,SummerAccHeat,SummerTmaxDay,SummerTavg
0,0,1961,167,264,0.179406,-0.178050,98,357.05,243,293.634184
1,1,1962,148,250,0.119715,-0.154788,103,259.10,189,292.577670
2,2,1963,160,240,0.189688,-0.135459,81,247.05,182,292.920988
3,3,1964,160,235,0.132678,-0.120557,76,194.50,181,292.055921
4,4,1965,177,236,0.058178,-0.088667,60,102.90,179,291.286667
...,...,...,...,...,...,...,...,...,...,...
58,58,2019,162,258,0.174103,-0.251686,97,371.20,201,294.062371
59,59,2020,154,252,0.280900,-0.206033,99,512.10,189,295.388384
60,60,2021,150,266,0.143323,-0.216700,117,500.60,178,294.581624
61,61,2022,151,258,0.183307,-0.197952,108,448.50,218,294.480556
62,62,2023,151,263,0.147676,-0.193283,113,367.90,247,293.456195

In [8]:
df_summ.query("(Year >=2014)").SummerLength.mean()

np.float64(109.9)