In [10]:
import pandas as pd
import numpy as np

In [11]:
input_path = "../../../Data/GHCND/sydney-australia_summer_stats.csv"
df_summ = pd.read_csv(input_path)
df_summ

,Unnamed: 0,Year,SummerStart,SummerEnd,StartGrad,EndGrad,SummerLength,SummerAccHeat,SummerTmaxDay,SummerTavg
0,0,1961,198,247,0.042298,-0.064160,50,50.50,222,294.970000
1,1,1962,181,254,0.050942,-0.047475,74,89.70,236,295.241892
2,2,1963,173,253,0.055165,-0.070084,81,114.55,178,295.439506
3,3,1964,227,247,0.015545,-0.023384,21,33.90,246,296.007143
4,4,1965,200,242,0.026294,-0.036864,43,37.20,213,294.359302
...,...,...,...,...,...,...,...,...,...,...
58,58,2019,141,261,0.058981,-0.089370,121,223.15,207,295.985950
59,59,2020,151,259,0.044131,-0.064706,109,159.95,210,295.515596
60,60,2021,167,259,0.078854,-0.061552,93,161.30,216,296.009140
61,61,2022,187,270,0.073065,-0.130883,84,170.10,259,296.292857
62,62,2023,145,270,0.056205,-0.099215,126,262.70,167,296.402381

In [9]:
df_summ.query("(Year >= 2014)").SummerLength.mean()

np.float64(121.3)

In [12]:
# toronto
input_path = "../../../Data/GHCND/toronto_ont_summer_stats.csv"
df_summ = pd.read_csv(input_path)
df_summ

,Unnamed: 0,Year,SummerStart,SummerEnd,StartGrad,EndGrad,SummerLength,SummerAccHeat,SummerTmaxDay,SummerTavg
0,0,1961,167,264,0.179406,-0.178050,98,357.05,243,293.634184
1,1,1962,148,250,0.119715,-0.154788,103,259.10,189,292.577670
2,2,1963,160,240,0.189688,-0.135459,81,247.05,182,292.920988
3,3,1964,160,235,0.132678,-0.120557,76,194.50,181,292.055921
4,4,1965,177,236,0.058178,-0.088667,60,102.90,179,291.286667
...,...,...,...,...,...,...,...,...,...,...
58,58,2019,162,258,0.174103,-0.251686,97,371.20,201,294.062371
59,59,2020,154,252,0.280900,-0.206033,99,512.10,189,295.388384
60,60,2021,150,266,0.143323,-0.216700,117,500.60,178,294.581624
61,61,2022,151,258,0.183307,-0.197952,108,448.50,218,294.480556
62,62,2023,151,263,0.147676,-0.193283,113,367.90,247,293.456195

In [14]:
df_summ.query("(Year >=2014)").SummerLength.mean()

np.float64(109.9)