In [2]:
import pandas as pd
import numpy as np

In [3]:
input_path = "../../../Data/GHCND/msp_minnesota_summer_stats.csv"
df_summ = pd.read_csv(input_path)
df_summ

,Unnamed: 0,Year,SummerStart,SummerEnd,StartGrad,EndGrad,SummerLength,SummerAccHeat,SummerTmaxDay,SummerTavg
0,0,1961,165,243,0.205268,-0.146340,79,231.65,179,294.517722
1,1,1962,160,229,0.094240,-0.091589,70,117.60,179,293.053571
2,2,1963,162,244,0.197626,-0.127999,83,264.30,181,294.690361
3,3,1964,148,238,0.252824,-0.137940,91,334.00,213,294.718681
4,4,1965,162,231,0.134586,-0.155505,70,171.50,204,294.252143
...,...,...,...,...,...,...,...,...,...,...
58,58,2019,159,253,0.124908,-0.283768,95,304.10,200,295.018421
59,59,2020,152,245,0.225283,-0.223677,94,412.80,238,296.393617
60,60,2021,146,260,0.192252,-0.196772,115,533.40,156,296.270000
61,61,2022,150,254,0.256945,-0.165532,105,443.30,171,296.127143
62,62,2023,140,262,0.216950,-0.239557,123,525.30,235,296.108537

In [4]:
df_summ.query("(Year > 1990) & (Year <= 2000)").SummerLength.mean()

np.float64(83.2)

In [11]:
df_summ.query("(Year >=2014)").SummerEnd.mean()

np.float64(254.2)

In [9]:
df_summ.query("(Year <=1970)").SummerEnd.mean()

np.float64(240.9)

In [12]:
# toronto
input_path = "../../../Data/GHCND/toronto_ont_summer_stats.csv"
df_summ = pd.read_csv(input_path)
df_summ

,Unnamed: 0,Year,SummerStart,SummerEnd,StartGrad,EndGrad,SummerLength,SummerAccHeat,SummerTmaxDay,SummerTavg
0,0,1961,167,264,0.179406,-0.178050,98,357.05,243,293.634184
1,1,1962,148,250,0.119715,-0.154788,103,259.10,189,292.577670
2,2,1963,160,240,0.189688,-0.135459,81,247.05,182,292.920988
3,3,1964,160,235,0.132678,-0.120557,76,194.50,181,292.055921
4,4,1965,177,236,0.058178,-0.088667,60,102.90,179,291.286667
...,...,...,...,...,...,...,...,...,...,...
58,58,2019,162,258,0.174103,-0.251686,97,371.20,201,294.062371
59,59,2020,154,252,0.280900,-0.206033,99,512.10,189,295.388384
60,60,2021,150,266,0.143323,-0.216700,117,500.60,178,294.581624
61,61,2022,151,258,0.183307,-0.197952,108,448.50,218,294.480556
62,62,2023,151,263,0.147676,-0.193283,113,367.90,247,293.456195

In [14]:
df_summ.query("(Year >=2014)").SummerLength.mean()

np.float64(109.9)